
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/uart_top 

module baud_rate_generator(clock, reset, enb_tx, enb_rx);
  input clock, reset;
  output enb_tx, enb_rx;
  wire clock, reset;
  wire enb_tx, enb_rx;
  wire [13:0] counter_rx;
  wire [13:0] counter_tx;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_14, n_15, n_16, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_57, n_58, n_59, n_60, n_62, n_63, n_64;
  wire n_65, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_89, n_90;
  wire n_91, n_92, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103;
  DFFHQX1 enb_rx_reg(.CK (clock), .D (n_79), .Q (enb_rx));
  DFFHQX1 enb_tx_reg(.CK (clock), .D (n_78), .Q (enb_tx));
  NOR2XL g713(.A (n_91), .B (reset), .Y (n_79));
  AOI21X2 g714(.A0 (n_76), .A1 (n_74), .B0 (reset), .Y (n_91));
  NOR2X1 g715(.A (n_90), .B (reset), .Y (n_78));
  NOR2X1 g716(.A (n_77), .B (reset), .Y (n_90));
  NOR3X1 g717(.A (n_75), .B (n_70), .C (n_89), .Y (n_77));
  AND4X2 g718(.A (n_73), .B (n_72), .C (counter_rx[7]), .D
       (counter_rx[3]), .Y (n_76));
  NAND3BX1 g719(.AN (counter_tx[12]), .B (n_69), .C (counter_tx[13]),
       .Y (n_75));
  AND3X2 g720(.A (n_71), .B (n_68), .C (counter_rx[1]), .Y (n_74));
  NOR3X1 g721(.A (n_101), .B (counter_rx[4]), .C (counter_rx[2]), .Y
       (n_73));
  NOR3X1 g722(.A (counter_rx[5]), .B (counter_rx[13]), .C
       (counter_rx[12]), .Y (n_72));
  NOR3X1 g723(.A (counter_rx[8]), .B (counter_rx[6]), .C
       (counter_rx[0]), .Y (n_71));
  NAND4BXL g724(.AN (counter_tx[8]), .B (counter_tx[7]), .C
       (counter_tx[5]), .D (counter_tx[11]), .Y (n_70));
  NOR4X1 g725(.A (counter_tx[6]), .B (counter_tx[4]), .C
       (counter_tx[10]), .D (counter_tx[9]), .Y (n_69));
  NAND4X2 g726(.A (counter_tx[3]), .B (counter_tx[0]), .C
       (counter_tx[2]), .D (counter_tx[1]), .Y (n_89));
  NOR2X1 g727(.A (counter_rx[11]), .B (counter_rx[10]), .Y (n_68));
  DFFTRX2 \counter_rx_reg[0] (.CK (clock), .D (n_92), .RN (n_91), .Q
       (counter_rx[0]), .QN (n_92));
  DFFTRXL \counter_rx_reg[10] (.CK (clock), .D (n_55), .RN (n_91), .Q
       (counter_rx[10]), .QN (UNCONNECTED));
  EDFFTRX1 \counter_rx_reg[11] (.CK (clock), .D (n_6), .E (n_54), .RN
       (n_91), .Q (counter_rx[11]), .QN (n_6));
  DFFX1 \counter_rx_reg[12] (.CK (clock), .D (n_58), .Q
       (counter_rx[12]), .QN (n_8));
  EDFFTRX1 \counter_rx_reg[13] (.CK (clock), .D (n_4), .E (n_43), .RN
       (n_91), .Q (counter_rx[13]), .QN (n_4));
  DFFTRX2 \counter_rx_reg[1] (.CK (clock), .D (n_19), .RN (n_91), .Q
       (counter_rx[1]), .QN (UNCONNECTED0));
  DFFTRXL \counter_rx_reg[2] (.CK (clock), .D (n_28), .RN (n_91), .Q
       (counter_rx[2]), .QN (UNCONNECTED1));
  DFFTRXL \counter_rx_reg[3] (.CK (clock), .D (n_48), .RN (n_91), .Q
       (counter_rx[3]), .QN (UNCONNECTED2));
  DFFTRX1 \counter_rx_reg[4] (.CK (clock), .D (n_34), .RN (n_91), .Q
       (counter_rx[4]), .QN (n_97));
  DFFTRX1 \counter_rx_reg[5] (.CK (clock), .D (n_39), .RN (n_91), .Q
       (counter_rx[5]), .QN (UNCONNECTED3));
  DFFTRX1 \counter_rx_reg[6] (.CK (clock), .D (n_41), .RN (n_91), .Q
       (counter_rx[6]), .QN (n_99));
  EDFFTRX1 \counter_rx_reg[7] (.CK (clock), .D (n_3), .E (n_36), .RN
       (n_91), .Q (counter_rx[7]), .QN (n_3));
  DFFX1 \counter_rx_reg[8] (.CK (clock), .D (n_51), .Q (counter_rx[8]),
       .QN (n_9));
  DFFTRX4 \counter_tx_reg[0] (.CK (clock), .D (n_7), .RN (n_90), .Q
       (counter_tx[0]), .QN (n_7));
  DFFTRX1 \counter_tx_reg[10] (.CK (clock), .D (n_63), .RN (n_90), .Q
       (counter_tx[10]), .QN (n_96));
  DFFTRXL \counter_tx_reg[11] (.CK (clock), .D (n_65), .RN (n_90), .Q
       (counter_tx[11]), .QN (UNCONNECTED4));
  DFFTRX1 \counter_tx_reg[12] (.CK (clock), .D (n_94), .RN (n_90), .Q
       (counter_tx[12]), .QN (UNCONNECTED5));
  DFFTRXL \counter_tx_reg[13] (.CK (clock), .D (n_67), .RN (n_90), .Q
       (counter_tx[13]), .QN (UNCONNECTED6));
  DFFTRX4 \counter_tx_reg[1] (.CK (clock), .D (n_18), .RN (n_90), .Q
       (counter_tx[1]), .QN (UNCONNECTED7));
  DFFTRX4 \counter_tx_reg[2] (.CK (clock), .D (n_40), .RN (n_90), .Q
       (counter_tx[2]), .QN (UNCONNECTED8));
  DFFTRX4 \counter_tx_reg[3] (.CK (clock), .D (n_57), .RN (n_90), .Q
       (counter_tx[3]), .QN (UNCONNECTED9));
  DFFTRX2 \counter_tx_reg[4] (.CK (clock), .D (n_20), .RN (n_90), .Q
       (counter_tx[4]), .QN (n_98));
  DFFTRX2 \counter_tx_reg[5] (.CK (clock), .D (n_27), .RN (n_90), .Q
       (counter_tx[5]), .QN (UNCONNECTED10));
  DFFTRX1 \counter_tx_reg[6] (.CK (clock), .D (n_33), .RN (n_90), .Q
       (counter_tx[6]), .QN (n_100));
  DFFTRX1 \counter_tx_reg[7] (.CK (clock), .D (n_38), .RN (n_90), .Q
       (counter_tx[7]), .QN (UNCONNECTED11));
  DFFTRX1 \counter_tx_reg[8] (.CK (clock), .D (n_42), .RN (n_90), .Q
       (counter_tx[8]), .QN (n_5));
  DFFTRXL \counter_tx_reg[9] (.CK (clock), .D (n_95), .RN (n_90), .Q
       (counter_tx[9]), .QN (UNCONNECTED12));
  OAI2BB2XL g1603(.A0N (counter_tx[13]), .A1N (n_64), .B0 (n_64), .B1
       (counter_tx[13]), .Y (n_67));
  OAI2BB2XL g1608(.A0N (counter_tx[11]), .A1N (n_62), .B0 (n_62), .B1
       (counter_tx[11]), .Y (n_65));
  NAND2X1 g1610(.A (n_60), .B (counter_tx[12]), .Y (n_64));
  OAI2BB2XL g1611(.A0N (counter_tx[10]), .A1N (n_52), .B0 (n_52), .B1
       (counter_tx[10]), .Y (n_63));
  OR2X2 g1614(.A (n_52), .B (n_96), .Y (n_62));
  NOR2X2 g1616(.A (n_52), .B (n_15), .Y (n_60));
  OAI31X1 g1625(.A0 (n_2), .A1 (n_9), .A2 (counter_rx[9]), .B0 (n_53),
       .Y (n_59));
  OAI32X1 g1626(.A0 (n_23), .A1 (n_2), .A2 (counter_rx[12]), .B0
       (n_49), .B1 (n_8), .Y (n_58));
  OAI2BB2XL g1627(.A0N (counter_tx[3]), .A1N (n_35), .B0 (n_35), .B1
       (counter_tx[3]), .Y (n_57));
  ADDHXL g1629(.A (counter_rx[10]), .B (n_44), .S (n_55), .CO (n_54));
  NAND2X1 g1633(.A (n_50), .B (counter_rx[9]), .Y (n_53));
  NAND2X1 g1634(.A (n_37), .B (counter_tx[9]), .Y (n_52));
  OAI22XL g1635(.A0 (n_2), .A1 (counter_rx[8]), .B0 (n_9), .B1 (n_46),
       .Y (n_51));
  OAI2BB1XL g1639(.A0N (n_91), .A1N (n_9), .B0 (n_46), .Y (n_50));
  AOI21XL g1640(.A0 (n_23), .A1 (n_91), .B0 (n_45), .Y (n_49));
  OAI2BB2XL g1641(.A0N (counter_rx[3]), .A1N (n_26), .B0 (n_26), .B1
       (counter_rx[3]), .Y (n_48));
  INVXL g1646(.A (n_46), .Y (n_45));
  NAND2X1 g1647(.A (n_1), .B (n_91), .Y (n_46));
  NOR2X1 g1648(.A (n_1), .B (n_16), .Y (n_44));
  NOR3X1 g1649(.A (n_1), .B (n_23), .C (n_8), .Y (n_43));
  OAI2BB2XL g1650(.A0N (counter_tx[8]), .A1N (n_102), .B0 (n_102), .B1
       (counter_tx[8]), .Y (n_42));
  OAI2BB2XL g1651(.A0N (counter_rx[6]), .A1N (n_103), .B0 (n_103), .B1
       (counter_rx[6]), .Y (n_41));
  OAI2BB2XL g1652(.A0N (counter_tx[2]), .A1N (n_10), .B0 (n_10), .B1
       (counter_tx[2]), .Y (n_40));
  OAI2BB2XL g1653(.A0N (counter_rx[5]), .A1N (n_31), .B0 (n_31), .B1
       (counter_rx[5]), .Y (n_39));
  OAI2BB2XL g1654(.A0N (counter_tx[7]), .A1N (n_32), .B0 (n_32), .B1
       (counter_tx[7]), .Y (n_38));
  NOR2X1 g1657(.A (n_102), .B (n_5), .Y (n_37));
  NOR2X1 g1658(.A (n_103), .B (n_99), .Y (n_36));
  NAND2BX1 g1659(.AN (n_10), .B (counter_tx[2]), .Y (n_35));
  OAI2BB2XL g1662(.A0N (counter_rx[4]), .A1N (n_22), .B0 (n_22), .B1
       (counter_rx[4]), .Y (n_34));
  OAI2BB2XL g1663(.A0N (counter_tx[6]), .A1N (n_25), .B0 (n_25), .B1
       (counter_tx[6]), .Y (n_33));
  OR2X2 g1664(.A (n_25), .B (n_100), .Y (n_32));
  OR2X2 g1665(.A (n_22), .B (n_97), .Y (n_31));
  OAI2BB2XL g1669(.A0N (counter_rx[2]), .A1N (n_0), .B0 (n_0), .B1
       (counter_rx[2]), .Y (n_28));
  OAI2BB2XL g1670(.A0N (counter_tx[5]), .A1N (n_14), .B0 (n_14), .B1
       (counter_tx[5]), .Y (n_27));
  NAND2BX1 g1673(.AN (n_0), .B (counter_rx[2]), .Y (n_26));
  INVX1 g1674(.A (n_24), .Y (n_25));
  NOR2X1 g1675(.A (n_89), .B (n_11), .Y (n_24));
  NAND3BX1 g1676(.AN (n_16), .B (counter_rx[10]), .C (counter_rx[11]),
       .Y (n_23));
  INVX1 g1677(.A (n_21), .Y (n_22));
  NOR2X2 g1678(.A (n_0), .B (n_12), .Y (n_21));
  OAI2BB2XL g1679(.A0N (counter_tx[4]), .A1N (n_89), .B0 (n_89), .B1
       (counter_tx[4]), .Y (n_20));
  XOR2X1 g1680(.A (counter_rx[0]), .B (counter_rx[1]), .Y (n_19));
  MXI2X1 g1681(.S0 (counter_tx[1]), .B (counter_tx[0]), .A (n_7), .Y
       (n_18));
  NAND2X1 g1683(.A (counter_rx[9]), .B (counter_rx[8]), .Y (n_16));
  NAND2X1 g1684(.A (counter_tx[10]), .B (counter_tx[11]), .Y (n_15));
  OR2X2 g1685(.A (n_89), .B (n_98), .Y (n_14));
  NAND2X1 g1688(.A (counter_rx[3]), .B (counter_rx[2]), .Y (n_12));
  NAND2X1 g1689(.A (counter_tx[4]), .B (counter_tx[5]), .Y (n_11));
  NAND2X1 g1690(.A (counter_tx[0]), .B (counter_tx[1]), .Y (n_10));
  NAND2BX1 g2(.AN (n_1), .B (n_91), .Y (n_2));
  NAND3BX1 g1700(.AN (n_103), .B (counter_rx[6]), .C (counter_rx[7]),
       .Y (n_1));
  NAND2BX1 g1701(.AN (n_92), .B (counter_rx[1]), .Y (n_0));
  XOR2X1 g1702(.A (counter_tx[12]), .B (n_60), .Y (n_94));
  XOR2X1 g1703(.A (counter_tx[9]), .B (n_37), .Y (n_95));
  DFFX1 \counter_rx_reg[9] (.CK (clock), .D (n_59), .Q (counter_rx[9]),
       .QN (n_101));
  NAND3X1 g1706(.A (counter_tx[6]), .B (counter_tx[7]), .C (n_24), .Y
       (n_102));
  NAND3X2 g1707(.A (n_21), .B (counter_rx[4]), .C (counter_rx[5]), .Y
       (n_103));
endmodule

module uart_reciver(clk, rst, rx, rdy_clr, clk_en, rdy, data_out);
  input clk, rst, rx, rdy_clr, clk_en;
  output rdy;
  output [7:0] data_out;
  wire clk, rst, rx, rdy_clr, clk_en;
  wire rdy;
  wire [7:0] data_out;
  wire [3:0] index;
  wire [3:0] sample;
  wire [1:0] state;
  wire [7:0] temp_register;
  wire UNCONNECTED13, UNCONNECTED14, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_11, n_12, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_89, n_90, n_92, n_93, n_94, n_95, n_98, n_101;
  wire n_102, n_103, n_104, n_119, n_120, n_121, n_122, n_123;
  DFFHQX1 \data_out_reg[0] (.CK (clk), .D (n_80), .Q (data_out[0]));
  DFFHQX1 \data_out_reg[1] (.CK (clk), .D (n_78), .Q (data_out[1]));
  DFFHQX1 \data_out_reg[2] (.CK (clk), .D (n_74), .Q (data_out[2]));
  DFFHQX1 \data_out_reg[3] (.CK (clk), .D (n_76), .Q (data_out[3]));
  DFFHQX1 \data_out_reg[4] (.CK (clk), .D (n_72), .Q (data_out[4]));
  DFFHQX1 \data_out_reg[5] (.CK (clk), .D (n_70), .Q (data_out[5]));
  DFFHQX1 \data_out_reg[6] (.CK (clk), .D (n_68), .Q (data_out[6]));
  DFFHQX1 \data_out_reg[7] (.CK (clk), .D (n_81), .Q (data_out[7]));
  DFFHQX1 \index_reg[1] (.CK (clk), .D (n_86), .Q (index[1]));
  SDFFHQX1 \sample_reg[0] (.CK (clk), .D (n_38), .SI (n_32), .SE
       (sample[0]), .Q (sample[0]));
  SDFFTRX1 \sample_reg[1] (.CK (clk), .D (sample[0]), .RN (n_38), .SI
       (n_45), .SE (sample[1]), .Q (sample[1]), .QN (UNCONNECTED13));
  DFFX1 \sample_reg[3] (.CK (clk), .D (n_84), .Q (sample[3]), .QN
       (n_12));
  DFFX4 \state_reg[0] (.CK (clk), .D (n_98), .Q (state[0]), .QN (n_8));
  DFFX2 \state_reg[1] (.CK (clk), .D (n_61), .Q (state[1]), .QN (n_7));
  DFFHQX1 \temp_register_reg[0] (.CK (clk), .D (n_103), .Q
       (temp_register[0]));
  DFFHQX1 \temp_register_reg[1] (.CK (clk), .D (n_121), .Q
       (temp_register[1]));
  DFFHQX1 \temp_register_reg[2] (.CK (clk), .D (n_104), .Q
       (temp_register[2]));
  DFFHQX1 \temp_register_reg[3] (.CK (clk), .D (n_123), .Q
       (temp_register[3]));
  DFFHQX1 \temp_register_reg[4] (.CK (clk), .D (n_101), .Q
       (temp_register[4]));
  DFFHQX1 \temp_register_reg[5] (.CK (clk), .D (n_122), .Q
       (temp_register[5]));
  DFFHQX1 \temp_register_reg[6] (.CK (clk), .D (n_102), .Q
       (temp_register[6]));
  OAI21XL g2705(.A0 (n_49), .A1 (n_30), .B0 (n_94), .Y (n_104));
  OAI21XL g2706(.A0 (n_49), .A1 (n_31), .B0 (n_95), .Y (n_103));
  OAI21XL g2707(.A0 (n_56), .A1 (n_30), .B0 (n_92), .Y (n_102));
  OAI21XL g2708(.A0 (n_56), .A1 (n_31), .B0 (n_93), .Y (n_101));
  OAI22X1 g2711(.A0 (n_87), .A1 (rst), .B0 (n_25), .B1 (n_27), .Y
       (n_98));
  OAI21XL g2727(.A0 (n_64), .A1 (n_17), .B0 (temp_register[0]), .Y
       (n_95));
  OAI21XL g2728(.A0 (n_64), .A1 (n_22), .B0 (temp_register[2]), .Y
       (n_94));
  OAI21XL g2729(.A0 (n_65), .A1 (n_17), .B0 (temp_register[4]), .Y
       (n_93));
  OAI21XL g2730(.A0 (n_65), .A1 (n_22), .B0 (temp_register[6]), .Y
       (n_92));
  OAI22XL g2732(.A0 (n_4), .A1 (n_62), .B0 (n_54), .B1 (n_30), .Y
       (n_90));
  OAI22X1 g2733(.A0 (n_59), .A1 (rst), .B0 (n_8), .B1 (n_28), .Y
       (n_89));
  AOI211X1 g2738(.A0 (state[0]), .A1 (n_9), .B0 (n_51), .C0 (n_44), .Y
       (n_87));
  OAI32XL g2739(.A0 (n_2), .A1 (n_6), .A2 (n_23), .B0 (n_48), .B1
       (n_18), .Y (n_86));
  OAI21XL g2740(.A0 (n_53), .A1 (rst), .B0 (n_18), .Y (n_85));
  OAI32X1 g2741(.A0 (n_29), .A1 (sample[3]), .A2 (n_39), .B0 (n_46),
       .B1 (n_12), .Y (n_84));
  OAI2BB1XL g2742(.A0N (n_5), .A1N (n_50), .B0 (n_18), .Y (n_83));
  OAI32X1 g2743(.A0 (n_24), .A1 (sample[2]), .A2 (n_39), .B0 (n_47),
       .B1 (n_120), .Y (n_82));
  OAI2BB2XL g2744(.A0N (n_52), .A1N (data_out[7]), .B0 (n_4), .B1
       (n_57), .Y (n_81));
  INVX1 g2745(.A (n_79), .Y (n_80));
  AOI22XL g2746(.A0 (temp_register[0]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[0]), .Y (n_79));
  INVX1 g2747(.A (n_77), .Y (n_78));
  AOI22XL g2748(.A0 (temp_register[1]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[1]), .Y (n_77));
  INVX1 g2749(.A (n_75), .Y (n_76));
  AOI22XL g2750(.A0 (temp_register[3]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[3]), .Y (n_75));
  INVX1 g2751(.A (n_73), .Y (n_74));
  AOI22XL g2752(.A0 (temp_register[2]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[2]), .Y (n_73));
  INVX1 g2753(.A (n_71), .Y (n_72));
  AOI22XL g2754(.A0 (temp_register[4]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[4]), .Y (n_71));
  INVX1 g2755(.A (n_69), .Y (n_70));
  AOI22XL g2756(.A0 (temp_register[5]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[5]), .Y (n_69));
  INVX1 g2757(.A (n_67), .Y (n_68));
  AOI22XL g2758(.A0 (temp_register[6]), .A1 (n_58), .B0 (n_52), .B1
       (data_out[6]), .Y (n_67));
  OAI33X1 g2759(.A0 (n_2), .A1 (n_6), .A2 (n_18), .B0 (n_51), .B1
       (n_11), .B2 (rst), .Y (n_66));
  NOR2X1 g2760(.A (n_55), .B (rst), .Y (n_65));
  AND2X2 g2761(.A (n_49), .B (n_5), .Y (n_64));
  OAI31XL g2762(.A0 (n_119), .A1 (rdy_clr), .A2 (rst), .B0 (n_57), .Y
       (n_63));
  AOI21X1 g2763(.A0 (n_41), .A1 (n_5), .B0 (n_26), .Y (n_62));
  OAI221XL g2764(.A0 (n_2), .A1 (n_28), .B0 (clk_en), .B1 (n_16), .C0
       (n_3), .Y (n_61));
  OAI21XL g2765(.A0 (n_40), .A1 (rst), .B0 (n_27), .Y (n_60));
  AOI2BB2X1 g2766(.A0N (n_2), .A1N (index[0]), .B0 (n_42), .B1
       (index[0]), .Y (n_59));
  INVX1 g2767(.A (n_58), .Y (n_57));
  NOR2X1 g2768(.A (n_43), .B (rst), .Y (n_58));
  INVX1 g2769(.A (n_55), .Y (n_56));
  NOR2X1 g2770(.A (n_41), .B (index[0]), .Y (n_55));
  INVX1 g2771(.A (n_53), .Y (n_54));
  NOR2X1 g2772(.A (n_41), .B (n_6), .Y (n_53));
  AND2X2 g2773(.A (n_43), .B (n_5), .Y (n_52));
  NOR2X1 g2774(.A (n_42), .B (state[0]), .Y (n_51));
  NAND2X1 g2775(.A (n_40), .B (index[0]), .Y (n_50));
  NAND2X1 g2776(.A (n_40), .B (n_6), .Y (n_49));
  AOI21XL g2777(.A0 (n_14), .A1 (state[0]), .B0 (n_42), .Y (n_48));
  AOI21X1 g2778(.A0 (n_24), .A1 (n_35), .B0 (n_32), .Y (n_47));
  AOI21X1 g2779(.A0 (n_29), .A1 (n_35), .B0 (n_32), .Y (n_46));
  NAND2BX1 g2780(.AN (n_32), .B (n_1), .Y (n_45));
  AOI21XL g2781(.A0 (n_36), .A1 (index[2]), .B0 (n_25), .Y (n_44));
  NAND2XL g2782(.A (n_20), .B (n_37), .Y (n_43));
  NAND2BX1 g2783(.AN (state[1]), .B (n_37), .Y (n_42));
  NAND2X1 g2785(.A (n_34), .B (index[2]), .Y (n_41));
  AND2X2 g2786(.A (n_34), .B (n_11), .Y (n_40));
  INVX1 g2789(.A (n_39), .Y (n_38));
  NAND3X1 g2790(.A (n_33), .B (clk_en), .C (n_5), .Y (n_39));
  NOR2X1 g2791(.A (n_29), .B (n_15), .Y (n_37));
  NOR2X1 g2793(.A (n_29), .B (n_12), .Y (n_36));
  OAI21XL g2794(.A0 (n_21), .A1 (rst), .B0 (n_16), .Y (n_35));
  NOR4X1 g2795(.A (n_0), .B (n_25), .C (sample[0]), .D (sample[2]), .Y
       (n_34));
  OAI211X1 g2796(.A0 (rx), .A1 (state[1]), .B0 (n_19), .C0 (n_25), .Y
       (n_33));
  OAI22X1 g2797(.A0 (n_8), .A1 (n_16), .B0 (clk_en), .B1 (rst), .Y
       (n_32));
  NAND2X1 g2798(.A (rx), .B (n_22), .Y (n_31));
  NAND2X1 g2800(.A (rx), .B (n_17), .Y (n_30));
  NAND3X1 g2801(.A (sample[0]), .B (sample[1]), .C (sample[2]), .Y
       (n_29));
  NAND3X1 g2802(.A (index[0]), .B (index[2]), .C (n_17), .Y (n_28));
  INVX1 g2803(.A (n_27), .Y (n_26));
  AOI21X1 g2804(.A0 (n_6), .A1 (n_5), .B0 (n_22), .Y (n_27));
  NAND2X1 g2808(.A (n_7), .B (state[0]), .Y (n_25));
  NAND2X1 g2809(.A (sample[0]), .B (sample[1]), .Y (n_24));
  INVXL g2810(.A (n_22), .Y (n_23));
  NOR2X1 g2811(.A (index[1]), .B (rst), .Y (n_22));
  AND2X2 g2812(.A (rx), .B (n_8), .Y (n_21));
  INVX1 g2813(.A (n_20), .Y (n_19));
  NOR2X1 g2814(.A (n_7), .B (state[0]), .Y (n_20));
  INVX1 g2815(.A (n_18), .Y (n_17));
  NAND2X1 g2816(.A (index[1]), .B (n_5), .Y (n_18));
  NAND2X1 g2817(.A (state[1]), .B (n_5), .Y (n_16));
  NAND2X1 g2818(.A (sample[3]), .B (clk_en), .Y (n_15));
  NAND2X1 g2819(.A (n_11), .B (index[0]), .Y (n_14));
  INVX1 g2825(.A (clk_en), .Y (n_9));
  INVX1 g2829(.A (rst), .Y (n_5));
  NAND3BX1 g2(.AN (n_36), .B (n_20), .C (n_5), .Y (n_3));
  NAND2BX1 g2832(.AN (n_25), .B (n_37), .Y (n_2));
  NAND2BX1 g2833(.AN (sample[0]), .B (n_35), .Y (n_1));
  NAND3BX1 g2834(.AN (sample[1]), .B (sample[3]), .C (clk_en), .Y
       (n_0));
  DFFX1 rdy_reg(.CK (clk), .D (n_63), .Q (rdy), .QN (n_119));
  DFFX1 \index_reg[2] (.CK (clk), .D (n_66), .Q (index[2]), .QN (n_11));
  DFFX1 \sample_reg[2] (.CK (clk), .D (n_82), .Q (sample[2]), .QN
       (n_120));
  DFFX1 \index_reg[0] (.CK (clk), .D (n_89), .Q (index[0]), .QN (n_6));
  DFFX1 \temp_register_reg[7] (.CK (clk), .D (n_90), .Q
       (UNCONNECTED14), .QN (n_4));
  OAI2BB2XL g2845(.A0N (n_83), .A1N (temp_register[1]), .B0 (n_50), .B1
       (n_31), .Y (n_121));
  OAI2BB2XL g2846(.A0N (n_85), .A1N (temp_register[5]), .B0 (n_54), .B1
       (n_31), .Y (n_122));
  OAI2BB2XL g2847(.A0N (n_60), .A1N (temp_register[3]), .B0 (n_50), .B1
       (n_30), .Y (n_123));
endmodule

module transmitter(clk, wr_enb, enb, rst, data_in, tx, busy);
  input clk, wr_enb, enb, rst;
  input [7:0] data_in;
  output tx, busy;
  wire clk, wr_enb, enb, rst;
  wire [7:0] data_in;
  wire tx, busy;
  wire [1:0] state;
  wire [2:0] index;
  wire [7:0] data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57;
  OR2X2 g414(.A (state[1]), .B (state[0]), .Y (busy));
  DFFHQX1 tx_reg(.CK (clk), .D (n_57), .Q (tx));
  NAND4X1 g1379(.A (n_20), .B (busy), .C (n_56), .D (n_18), .Y (n_57));
  DFFHQX1 \index_reg[1] (.CK (clk), .D (n_54), .Q (index[1]));
  OAI211X1 g1382(.A0 (n_50), .A1 (rst), .B0 (enb), .C0 (n_14), .Y
       (n_56));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_52), .Q (state[0]));
  NAND2XL g1384(.A (n_51), .B (n_41), .Y (n_55));
  OAI21XL g1385(.A0 (index[1]), .A1 (n_26), .B0 (n_53), .Y (n_54));
  DFFHQX1 \data_reg[2] (.CK (clk), .D (n_49), .Q (data[2]));
  DFFHQX1 \data_reg[7] (.CK (clk), .D (n_42), .Q (data[7]));
  DFFHQX1 \data_reg[3] (.CK (clk), .D (n_48), .Q (data[3]));
  DFFHQX1 \data_reg[0] (.CK (clk), .D (n_43), .Q (data[0]));
  DFFHQX1 \data_reg[4] (.CK (clk), .D (n_47), .Q (data[4]));
  DFFHQX1 \data_reg[5] (.CK (clk), .D (n_45), .Q (data[5]));
  DFFHQX1 \data_reg[1] (.CK (clk), .D (n_46), .Q (data[1]));
  DFFHQX1 \data_reg[6] (.CK (clk), .D (n_44), .Q (data[6]));
  OAI21XL g1395(.A0 (n_35), .A1 (n_19), .B0 (index[1]), .Y (n_53));
  OAI221XL g1396(.A0 (n_13), .A1 (n_9), .B0 (enb), .B1 (n_14), .C0
       (n_41), .Y (n_52));
  AOI22X1 g1397(.A0 (index[0]), .A1 (n_35), .B0 (n_3), .B1 (n_16), .Y
       (n_51));
  MX2X1 g1398(.S0 (index[1]), .B (n_37), .A (n_36), .Y (n_50));
  NOR2XL g1399(.A (n_34), .B (rst), .Y (n_49));
  NOR2XL g1400(.A (n_32), .B (rst), .Y (n_48));
  NOR2XL g1401(.A (n_31), .B (rst), .Y (n_47));
  NOR2XL g1402(.A (n_29), .B (rst), .Y (n_46));
  NOR2XL g1403(.A (n_30), .B (rst), .Y (n_45));
  NOR2XL g1404(.A (n_28), .B (rst), .Y (n_44));
  NOR2XL g1405(.A (n_33), .B (rst), .Y (n_43));
  NOR2XL g1406(.A (n_27), .B (rst), .Y (n_42));
  NAND2XL g1407(.A (n_38), .B (index[2]), .Y (n_41));
  INVX1 g1408(.A (n_39), .Y (n_40));
  AOI21XL g1409(.A0 (index[2]), .A1 (n_23), .B0 (n_38), .Y (n_39));
  SDFFHQX1 \state_reg[1] (.CK (clk), .D (n_12), .SI (n_7), .SE (n_11),
       .Q (state[1]));
  NOR2BX1 g1411(.AN (index[1]), .B (n_26), .Y (n_38));
  AOI21XL g1412(.A0 (n_17), .A1 (index[2]), .B0 (n_25), .Y (n_37));
  OAI21XL g1413(.A0 (n_15), .A1 (n_4), .B0 (n_24), .Y (n_36));
  OAI221XL g1414(.A0 (enb), .A1 (n_8), .B0 (n_13), .B1 (wr_enb), .C0
       (n_14), .Y (n_35));
  AOI22XL g1415(.A0 (n_22), .A1 (data_in[2]), .B0 (n_21), .B1
       (data[2]), .Y (n_34));
  AOI22XL g1416(.A0 (n_22), .A1 (data_in[0]), .B0 (n_21), .B1
       (data[0]), .Y (n_33));
  AOI22XL g1417(.A0 (n_22), .A1 (data_in[3]), .B0 (n_21), .B1
       (data[3]), .Y (n_32));
  AOI22XL g1418(.A0 (n_22), .A1 (data_in[4]), .B0 (n_21), .B1
       (data[4]), .Y (n_31));
  AOI22XL g1419(.A0 (n_22), .A1 (data_in[5]), .B0 (n_21), .B1
       (data[5]), .Y (n_30));
  AOI22XL g1420(.A0 (n_22), .A1 (data_in[1]), .B0 (n_21), .B1
       (data[1]), .Y (n_29));
  AOI22XL g1421(.A0 (n_22), .A1 (data_in[6]), .B0 (n_21), .B1
       (data[6]), .Y (n_28));
  AOI22XL g1422(.A0 (n_22), .A1 (data_in[7]), .B0 (n_21), .B1
       (data[7]), .Y (n_27));
  NAND2X1 g1423(.A (index[0]), .B (n_16), .Y (n_26));
  OAI32X1 g1424(.A0 (index[2]), .A1 (index[0]), .A2 (data[2]), .B0
       (n_5), .B1 (data[3]), .Y (n_25));
  AOI32X1 g1425(.A0 (n_4), .A1 (n_3), .A2 (data[0]), .B0 (n_6), .B1
       (data[1]), .Y (n_24));
  OAI21XL g1426(.A0 (n_10), .A1 (rst), .B0 (n_8), .Y (n_23));
  INVX1 g1427(.A (n_22), .Y (n_21));
  AND2X2 g1428(.A (n_1), .B (n_10), .Y (n_22));
  OR2X2 g1429(.A (n_11), .B (n_1), .Y (n_20));
  NOR2XL g1430(.A (n_6), .B (n_8), .Y (n_19));
  OAI21XL g1431(.A0 (tx), .A1 (rst), .B0 (n_0), .Y (n_18));
  OAI22X1 g1432(.A0 (index[0]), .A1 (data[6]), .B0 (n_3), .B1
       (data[7]), .Y (n_17));
  NOR3X1 g1433(.A (state[0]), .B (n_0), .C (n_8), .Y (n_16));
  AOI22X1 g1434(.A0 (n_3), .A1 (data[4]), .B0 (index[0]), .B1
       (data[5]), .Y (n_15));
  NAND2X1 g1435(.A (state[0]), .B (n_2), .Y (n_14));
  INVXL g1436(.A (n_13), .Y (n_12));
  NAND2X1 g1437(.A (n_1), .B (n_2), .Y (n_13));
  NAND2X1 g1438(.A (state[0]), .B (enb), .Y (n_11));
  INVXL g1439(.A (n_10), .Y (n_9));
  NOR2BX1 g1440(.AN (wr_enb), .B (state[0]), .Y (n_10));
  INVXL g1441(.A (n_8), .Y (n_7));
  NAND2X1 g1442(.A (state[1]), .B (n_2), .Y (n_8));
  INVX1 g1443(.A (n_5), .Y (n_6));
  NAND2X1 g1444(.A (n_4), .B (index[0]), .Y (n_5));
  INVX1 g1447(.A (rst), .Y (n_2));
  INVX1 g1448(.A (state[1]), .Y (n_1));
  INVX1 g1449(.A (enb), .Y (n_0));
  DFFX1 \index_reg[2] (.CK (clk), .D (n_40), .Q (index[2]), .QN (n_4));
  DFFX1 \index_reg[0] (.CK (clk), .D (n_55), .Q (index[0]), .QN (n_3));
endmodule

module uart_top(rst, clk, data_in, wr_en, rdy_clr, rdy, busy, data_out);
  input rst, clk, wr_en, rdy_clr;
  input [7:0] data_in;
  output rdy, busy;
  output [7:0] data_out;
  wire rst, clk, wr_en, rdy_clr;
  wire [7:0] data_in;
  wire rdy, busy;
  wire [7:0] data_out;
  wire rx_clk_en, tx_clk_en, tx_line;
  baud_rate_generator bg(.clock (clk), .reset (rst), .enb_tx
       (tx_clk_en), .enb_rx (rx_clk_en));
  uart_reciver rx_unit(.clk (clk), .rst (rst), .rx (tx_line), .rdy_clr
       (rdy_clr), .clk_en (rx_clk_en), .rdy (rdy), .data_out
       (data_out));
  transmitter tx_unit(.clk (clk), .wr_enb (wr_en), .enb (tx_clk_en),
       .rst (rst), .data_in (data_in), .tx (tx_line), .busy (busy));
endmodule

